[이영주] 연료 주입, 블랙잭 (Step 1)
next-step/java-blackjack pull request #36
Opened 2022-02-17 14:44 UTC by 0JUUU

안녕하세요! 선호 리뷰어님 😄

연료 주입과 블랙잭을 구현했습니다. 블랙잭의 구조를 그리고 이를 구현하는 것이 쉽지 않네요 😅
구현 시, `카드 분배`라는 행위의 책임에 대해 긴가민가하여 여쭤보고 싶은게 있습니다. 
`카드를 분배하는 행위`를 현재는 `전체 카드를 의미하는 클래스` `Deck` 에서 참가자들에게 나누는 형식으로 구현했습니다. 

이 `카드 분배` 를 `Dealer`가 관리하는 것이 맞는지 아니면 현재처럼 `Deck`에서 관리하는 것이 맞는지 리뷰어님의 의견이 궁금합니다 

잘 부탁드립니다!  감사합니다! 😊

2022-02-18 10:37 UTC, vsh123 requested changes
영주님 안녕하세요!
1단계 구현 잘해주셨네요 💯 

몇가지 코멘트를 남겼으니 확인부탁드리겠습니다!

2022-02-18 10:37 UTC, vsh123 commented on src/test/java/oilinjection/util/ParserTest.java
> +        assertThat(Parser.parse(input)).isEqualTo(rents);
`Parser.parse()`가 순서도 보장하는 List를 반환할거라는 확신이 없을 것 같아요! 현재 테스트는 `car2`객체가 먼저오면 실패를 할 수 있는 테스트인 것 같아요! 그래서 저는 보통 이런 테스트는 `assertAll`을 활용해서 아래와 같이 작성합니다!

```suggestion
        List<RentInfo> actual = Parser.parse(input);
        assertAll(
            () -> assertThat(actual).hasSize(2), 
            () -> assertThat(actual).containsAll(rents)
        );
```

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/RentCompany.java
> +            .collect(Collectors.groupingBy(RentInfo::getType, Collectors.summingInt(x -> 1)))
stream중에는 `Collectors.counting()`이라는 게 있습니다! 이것을 활용해볼 수 있을 것 같아요~
```suggestion
            .collect(Collectors.groupingBy(RentInfo::getType, Collectors.counting()))
```

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/RentCompany.java
> +        return RentCar.valueOf(type.toUpperCase());
존재하지 않는 type을 넣게되면, `IllegalArgumentException`이 발생하는데요! 이에 대한 validation을 진행해주면 어떨까요?

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/RentCar.java
> +    public boolean isImpossibleReservation(final int count) {
해당 메서드에 대한 테스트가 없는 것 같아요! 테스트를 작성해주면 어떨까요?

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/RentCar.java
> +public enum RentCar {
enum을 활용한 구현 👍

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/RentCompany.java
> +        rents.addAll(Collections.unmodifiableList(rentCars));
지역변수를 `Collections.unmodifiableList`로 한번 더 감쌀 필요가 있을까요? 영주님은 어떤 경우에 `Collections.unmodifiableList`를 선언해주시나요~?

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/car/Car.java
> +    }
이것에 Equals&HashCode를 Overriding하신 이유가 궁금합니다!

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/oilinjection/domain/car/Car.java
> +        return Math.ceil(getTripDistance() / getDistancePerLiter());
객체안에서는 메서드가 아닌 상태를 바로 호출해주면 어떨까요?

```suggestion
        return Math.ceil(this.tripDistance / getDistancePerLiter());
```

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/blackjack/domain/card/Cards.java
> +            .collect(Collectors.toList()));
Stream안에서 또다른 Stream을 호출하면서 가독성이 많이 떨어지는 것 같아요! 이런 경우에는 메서드로 분리를 해주면 어떨까요?

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/blackjack/domain/card/Deck.java
> +        cards.remove(card);
`draw()`시에 `cards`에서 draw된 카드가 remove되면 어떨까요? remove는 `cards.draw()`안에서 수행되어야할 것 같아요 :)

2022-02-18 10:37 UTC, vsh123 commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Cards cards;
> 연료 주입과 블랙잭을 구현했습니다. 블랙잭의 구조를 그리고 이를 구현하는 것이 쉽지 않네요 😅
구현 시, 카드 분배라는 행위의 책임에 대해 긴가민가하여 여쭤보고 싶은게 있습니다.
카드를 분배하는 행위를 현재는 전체 카드를 의미하는 클래스 Deck 에서 참가자들에게 나누는 형식으로 구현했습니다.
이 카드 분배 를 Dealer가 관리하는 것이 맞는지 아니면 현재처럼 Deck에서 관리하는 것이 맞는지 리뷰어님의 의견이 궁금합니다 

카드 분배를 Delaler가 한다면, Dealer가 Deck을 들고 있는 구조일까요? 아니면 Dealer가 Cards를 들고 있는 걸까요? 어느 부분이 되었던, 카드분배를 관리해야하는 곳은 `Cards`객체를 가지고 있는 쪽이 되어야할 것 같습니다 :) 요고는 구현하기 나름일 것 같아요!

2022-02-19 18:41 UTC, 0JUUU commented on src/main/java/oilinjection/util/Parser.java
> +public class Parser {
아하! 네이밍에 좀 더 신경을 써야겠네요! 클래스 이름을 구체적으로 명시하니 해당 클래스의 역할이 확실하게 와닿습니다! 말씀 감사합니다 😁
`oilInjection`에 Parser와 `blackjack`의 Parser를 각각 `RentInfoParser` / `PlayerNameParser`로 변경하였습니다!

2022-02-19 18:52 UTC, 0JUUU commented on src/test/java/oilinjection/util/ParserTest.java
> +        assertThat(Parser.parse(input)).isEqualTo(rents);
오.. 리뷰어님 덕분에 `assertAll` 에 대해 알게 되었습니다! 😄
선호 리뷰어님 말씀대로 순서가 바뀐다면, 해당 테스트는 실패하게 되네요! `size`와 `포함하는지에 대한 여부`를 판단하는 형식으로 변경하겠습니다!

2022-02-19 19:14 UTC, 0JUUU commented on src/main/java/oilinjection/domain/RentCompany.java
> +        return RentCar.valueOf(type.toUpperCase());
앗! 이 부분에 대해서는 제가 생각하지 못했던 예외처리네요! 말씀해주셔서 감사합니다! `자동차 종류에 대한 Enum` 클래스에서 valueOf를 진행할 때 `type에 맞는 자동차가 없다면`, `IllegarArgumentException`이 발생하도록 처리하였습니다!

```
private static final String NO_TYPE_EXCEPTION_MESSAGE_FORMAT = "[ERROR] %s 자동차는 회사에 존재하지 않습니다.";

private RentCar findRentCar(final String type) {
        try {
            return RentCar.valueOf(type.toUpperCase());
        } catch (IllegalArgumentException e) {
            throw new IllegalArgumentException(String.format(NO_TYPE_EXCEPTION_MESSAGE_FORMAT, type));
        }
    }
```
이와 같이 `RentCompany`에서 렌트카를 찾을 때, validate를 할 수 있도록 해봤습니다!

2022-02-20 08:02 UTC, 0JUUU commented on src/main/java/oilinjection/domain/RentCar.java
> +    public boolean isImpossibleReservation(final int count) {
앗! 이 메서드 관련 테스트가 없군요! 바로 작성하도록 하겠습니다 ㅎㅎ 감사합니다! 😄👍

2022-02-20 15:55 UTC, 0JUUU commented on src/main/java/oilinjection/domain/RentCompany.java
> +        rents.addAll(Collections.unmodifiableList(rentCars));
변경을 불가하게 하고 싶을 때, `Collections.unmodifiableList`를 이용합니다.
이 코멘트를 보고 다시 코드를 읽어봤을 때, 지역변수로 선언된 rentCars를 굳이 한 번 더 `Collections.unmodifiableList`로 감쌀 필요가 없다는 생각이 듭니다. 
지역 변수로 선언된 rentCars를 제거하고 rentCars에 할당된 내용을 바로 addAll에 추가하는 방법으로 코드를 변경하고자 합니다!

2022-02-20 16:00 UTC, 0JUUU commented on src/main/java/oilinjection/domain/car/Car.java
> +        return Math.ceil(getTripDistance() / getDistancePerLiter());
아하! 넵 감사합니다! 멤버변수로 갖고 있는 것을 굳이 getter로 호출할 필요가 없네요!

2022-02-20 16:03 UTC, 0JUUU commented on src/main/java/blackjack/domain/card/Cards.java
> +            .collect(Collectors.toList()));
코드를 찬찬히 읽어봤을 때, 말씀해주신 부분의 코드가 잘 읽히지 않았습니다. 메서드 분리를 통해 읽기 수월해졌네요! 말씀 감사합니다! 😄🤓

2022-02-20 16:08 UTC, 0JUUU commented on src/main/java/blackjack/domain/card/Deck.java
> +    private final Cards cards;
만약 Dealer가 카드 분배를 담당한다면, `Dealer`가 `Cards`을 갖고 있는 구조여야 한다고 생각했습니다! 
'Dealer에게 카드 분배의 책임을 넘겨준다면, 너무 하는 일이 많은 것 아닐까?' 하는 노파심에 카드 분배를 담당하는 Deck을 만들어 분배를 담당할 수 있도록 했습니다.
구현하기 나름인 정답이 없는 것이었군요! 말씀 감사합니다 ㅎㅎ 😁

2022-02-20 18:40 UTC, 0JUUU commented on src/main/java/blackjack/domain/card/Deck.java
> +        cards.remove(card);
아하! 말씀 감사합니다 ㅎㅎ '`Cards#draw` 안에서 remove를 호출하고 보니 굳이 메서드를 나눠야할까?' 라는 생각에 메서드를 제거했습니다.
어떻게 보면, `뽑는 것`과 `제거하는 것`은 각각 다른 일이라 메서드를 제거하고 보니 'draw에서 2가지 역할을 하나?' 라는 의문점이 드는데욥. 리뷰어님의 생각은 어떠신지 궁금합니다!

2022-02-20 19:14 UTC, 0JUUU commented on src/main/java/oilinjection/domain/car/Car.java
> +    }
RentCar에서 자동차가 잘 만들어졌는지에 대한 테스트를 진행하기 위해 넣었던 코드였습니다!
단순히 해당 테스트를 위해 만들어진 코드같네요... 
객체가 같은지 비교하는 것이 아닌 각각 들어있는 값이 같은지를 비교해보도록 하겠습니다! 😄 말씀 감사해요! 🤗

2022-02-20 19:46 UTC, 0JUUU commented on src/main/java/oilinjection/domain/RentCompany.java
> +            .collect(Collectors.groupingBy(RentInfo::getType, Collectors.summingInt(x -> 1)))
아하! `Collectors.counting()`을 보니 Long 타입으로 변환되기에 `validatePerCarType의 매개변수`를 `Long으로 변경`하고 내부 로직에서 `형변환`하는 형식으로 변경하였습니다!

2022-02-22 13:08 UTC, vsh123 commented on src/main/java/blackjack/domain/card/Deck.java
> +        cards.remove(card);
Cards에서 `draw`가 된다면 카드가 한장 제거되는 것까지가 하나의 흐름이라고 생각하는데요! 두개가 서로 다른 역할이 아니라 하나의 역할이라는 생각에서 리뷰를 드리게 되었습니다 :)

2022-02-22 14:27 UTC, vsh123 requested changes
영주님 안녕하세요!
Step1 너무 잘 구현해주셨네요 👍 

빠른 진행을 위해 이번 스텝은 머지하도록 하겠습니다.
몇가지 코멘트를 남겼는데, 요고는 다음 스텝에 함께 확인부탁드려요~

2022-02-22 14:27 UTC, vsh123 commented on src/main/java/blackjack/domain/card/Hands.java
> +        if (this.score.getValue() > DECISION_VALUE) {
객체에게 메세지를 던져보는 건 어떨까요?

2022-02-22 14:27 UTC, vsh123 commented on src/main/java/blackjack/BlackJackApplication.java
> +        return InputView.inputDrawFlag(player.getName()).equalsIgnoreCase("y");
매직넘버를 상수화해보면 어떨까요?

2022-02-22 14:27 UTC, vsh123 commented on src/main/java/blackjack/domain/judge/Judge.java
> +        if (playerScore <= LIMIT_SCORE && dealerScore > LIMIT_SCORE) {
여기 있는 모든 조건들(`dealerScore > LIMIT_SCORE`와 같은 것)을 `Participant`의 메서드로 만들어주면 어떨까요?

2022-02-22 14:27 UTC, vsh123 commented on src/main/java/blackjack/domain/judge/Judge.java
> +    public Map<String, String> getWinOrLose(final Participant dealer, final List<Participant> players) {
여기서는 첫번재는 Dealer, 두번째는 Player라는게 보장되어야하기 때문에
아래와 같이 구현 타입을 받아주면 어떨까요?

```suggestion
    public Map<String, String> getWinOrLose(final Dealer dealer, final List<Player> players) {
```

2022-02-22 14:29 UTC, merged

2022-03-01 15:07 UTC, 0JUUU commented on src/main/java/blackjack/domain/card/Deck.java
> +        cards.remove(card);
아하~ 생각해보니 그렇네요! 코멘트 감사합니다 ㅎㅎ

2022-03-01 16:06 UTC, 0JUUU commented on src/main/java/blackjack/BlackJackApplication.java
> +        return InputView.inputDrawFlag(player.getName()).equalsIgnoreCase("y");
앗! 말씀해주셔서 감사합니다! `YES` 라는 상수에 할당하였습니다!

2022-03-03 16:18 UTC, 0JUUU commented on src/main/java/blackjack/domain/judge/Judge.java
> +        if (playerScore <= LIMIT_SCORE && dealerScore > LIMIT_SCORE) {
오! get 하는 부분을 줄이면서 `Participant`에게 비교만 하라고 던져줄 수 있어 좋은 방법 같습니다. 적용해보겠습니다! 😁